# Generated by Django 5.0.4 on 2024-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20190815_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
