# Generated by Django 5.0.4 on 2024-05-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
